### PR TITLE
remove extra awaits

### PR DESCRIPTION
**Pull request by avioli**
Returning a Future accomplishes the same as awaiting for the result and returning it.

### CODE REVIEW

**Review by algodave — COMMENTED** [review]
@avioli Thank you for this PR! I only have one thought: since you're removing `await`s, shouldn't some `async` also be removed?

**Comment by avioli** [comment]
@algodave You could, but I think using the `async` keyword makes it clear to the user it is an async method and not a regular method, that returns a future.

**Comment by algodave** [comment]
@avioli I get your point but I'd like to follow Effective Dart's recommendations, more precisely:

 - [DON’T use async when it has no useful effect.](https://dart.dev/guides/language/effective-dart/usage#dont-use-async-when-it-has-no-useful-effect)
 
Using `async` without `await` tells Dart to automatically wrap the return value in a `Future`; I think we don't need this because the return value in the cases you spotted is a `Future` already.

**Comment by avioli** [comment]
Good point. I can update the http mixin when I'm at my dev machine.

**Comment by algodave** [comment]
@avioli I'm closing this PR for now, you may open a new one on top of the latest master if you like. Thanks!

**Pull request closed without merging**
